---
title: "Bogotá's Septima Verde"
author: "Ana Steiner, Aida Kazlauskatiė, Ciara Clarke, Marta Woroneicka and Hannah Schuller"
institute: "UCL"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: solarized-dark
      highlightLines: true
      countIncrementalSlides: false
---
class: align-left
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE, htmltools.preserve.raw = FALSE)
```
## Table of contents

---
## Bogota: the context 

---
## Past interventions

---
## International and national compliance

---
## Proposal

#### Main Objective:
- Develop a simulator using land surface temperature data and traffic data to identify optimal locations for a green corridor in Bogota.
- Account for how this will affect city-wide traffic flow and heat patterns before implementation.

#### Secondary Objectives:
- Transform key streets and corridors to prioritize greenery, public spaces, and pedestrian access. 
- Improve air quality by decreasing traffic congestion.

#### Outputs:
- A comprehensive simulator tool for planning green corridors.
- Capacity building programs for stakeholders to leverage the simulator in urban planning.
- A detailed proposal for the green corridor's location and design based on simulator outcomes.

---
## Case study

OFFER A LOGICAL workflow that incorporates EO data (at least one dataset required)

---
## Workflow: simulation

DISCUSS HOW DATA + WORKFLOW CAN BE INCORPORATED INTO THE CITY'S 'BUSINESS AS USUAL' DATA PIPELINES/WORKFLOWS

---
## Workflow: site selection

PROPOSE TIMELINE FOR PLAN

---
## Data inputs

PROPOSE ESTIMATED SPENDING PLAN

---
## Integration to Bogota's pipeline

PROPOSE OPPORTUNITIES FOR STAKEHOLDER ENGAGEMENT W/ PROJECT

---
## Stakeholder engagement

---
## GANTT and team details

---
## Limitations and mitigation of risk

---
## Future continuation

---